# 工作流名称
name: Flutter CI

#触发条件 当推送或拉取请求到main分支或dev分支时触发
on:
  push:
    branches: [master, dev]
  pull_request:
    branches:
      - master

# 权限
# 读取代码内容
permissions: 
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置Flutter环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      # 获取依赖
      - name: Get dependencies
        run: flutter pub get

      # 运行测试
      - name: Run test
        run: flutter test  

      # 检查代码格式
      - name: Check formatting
        run: dart format --set-exit-if-changed .

      # 静态分析
      - name: Analyze code
        run: flutter analyze